[debug] [2018-08-20T21:29:16.785Z] ----------------------------------------------------------------------
[debug] [2018-08-20T21:29:16.788Z] Command:       /usr/local/bin/node /usr/local/bin/firebase serve
[debug] [2018-08-20T21:29:16.788Z] CLI Version:   4.1.2
[debug] [2018-08-20T21:29:16.788Z] Platform:      darwin
[debug] [2018-08-20T21:29:16.788Z] Node Version:  v6.10.3
[debug] [2018-08-20T21:29:16.789Z] Time:          Mon Aug 20 2018 23:29:16 GMT+0200 (CEST)
[debug] [2018-08-20T21:29:16.789Z] ----------------------------------------------------------------------
[debug] 
[debug] [2018-08-20T21:29:16.800Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2018-08-20T21:29:16.800Z] > authorizing via signed-in user
[debug] [2018-08-20T21:29:16.802Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects/heltstjerne  
 
[debug] [2018-08-20T21:29:17.595Z] <<< HTTP RESPONSE 200
[debug] [2018-08-20T21:29:17.598Z] >>> HTTP REQUEST GET https://cloudresourcemanager.googleapis.com/v1/projects/heltstjerne  
 
[debug] [2018-08-20T21:29:18.710Z] <<< HTTP RESPONSE 200
[info] 
[info] === Serving from '/Users/thomassovik/firebase'...
[info] 
[debug] [2018-08-20T21:29:19.191Z] Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/logs'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:923:18)
    at Object.assertLogsPath (/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/emulator/logs.js:65:10)
    at new Controller (/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/cli/controller.js:77:32)
    at FunctionsEmulator.start (/usr/local/lib/node_modules/firebase-tools/lib/functionsEmulator.js:113:21)
    at Object.start (/usr/local/lib/node_modules/firebase-tools/lib/serve/functions.js:9:29)
    at /usr/local/lib/node_modules/firebase-tools/lib/serve/index.js:17:21
    at arrayMap (/usr/local/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:639:23)
    at Function.map (/usr/local/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:9554:14)
    at _serve (/usr/local/lib/node_modules/firebase-tools/lib/serve/index.js:15:7)
[error] 
[error] Error: An unexpected error has occurred.
